---

- name: install
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - tar
  - gzip

- name: set golang download url and checksum
  set_fact:
    url: https://dl.google.com/go/go1.9.3.linux-amd64.tar.gz
    checksum: sha256:a4da5f4c07dfda8194c4621611aeb7ceaab98af0b38bfb29e1be2ebb04c3556c
  when:
  - ansible_machine == "x86_64"
  - not goget_use_apt_golang

- name: set golang download url and checksum
  set_fact:
    url: https://dl.google.com/go/go1.9.3.linux-armv6l.tar.gz
    checksum: sha256:926d6cd6c21ef3419dca2e5da8d4b74b99592ab1feb5a62a4da244e6333189d2
  when:
  - ansible_machine == "aarch64"
  - not goget_use_apt_golang

- name: download latest golang
  get_url:
    dest: /usr/local/src
    url: "{{ url }}"
    checksum: "{{ checksum }}"
  register: dl
  when: not goget_use_apt_golang

- name: extract go
  command: "tar xf {{ dl.dest }}"
  args:
    chdir: /usr/local
  when: not goget_use_apt_golang

- name: apt install golang
  apt:
    name: golang-go
    state: present
  when: goget_use_apt_golang

- name: decide whether upx
  set_fact:
    use_upx: true
  when:
  - ansible_machine == "x86_64"
  - goget_goarch == ""
  - goget_upx|bool

- name: install upx
  apt:
    name: upx-ucl
    state: present
  when: use_upx is defined

- name: decide go get command if can strip
  set_fact:
    goget_command: "/usr/local/go/bin/go get -ldflags '-s' {{ goget_app }}"
  when: goget_strip

- name: decide go get command if cannot strip
  set_fact:
    goget_command: "/usr/local/go/bin/go get {{ goget_app }}"
  when: not goget_strip

- name: "build {{ goget_app }}"
  command: "{{ goget_command }}"
  environment:
    CGO_ENABLED: "{{ goget_cgo_enabled }}"
    GOPATH: "{{ goget_gopath }}"
    GOARM: "{{ goget_goarm }}"
    GOARCH: "{{ goget_goarch }}"

- name: upx binary
  command: "upx {{ goget_gopath }}/bin/{{ goget_app | basename }}"
  when: use_upx is defined

- name: uninstall
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - git
  - golang-go
  - tar
  - gzip
  when:
  - goget_uninstall

- name: uninstall upx
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - upx-ucl
  when:
  - use_upx is defined
  - goget_uninstall
